### ISSUE TITLE
Allow outputing files without zipping.

### ISSUE THREAD

**Issue by Maxyme** [micmurawski/poetry-plugin-lambda-build#10]
It would be nice if there was an option to output the generated packages to a dir instead of zipping it.
One reason for this, is to allow modifying the contents before uploading it to aws, which now requires unzipping then re-zipping.
Another use case is to allow zipping it with a terraform data.archive fill for hashing:
`source_code_hash = "sha256:${data.archive_file.name.output_base64sha256}"`

Thanks!

**Comment by micmurawski** [comment]
Sure thing!

**Comment by micmurawski** [comment]
@Maxyme 
run

```bash
poetry self add git+ssh://git@github.com/micmurawski/poetry-plugin-lambda-build@feature/add-optional-zipping
```

And see if that works for you. Notice that to disable zipping you need to drop `.zip` extensions from artifact paths

**Comment by Maxyme** [comment]
That works perfectly, thanks a lot!

**Comment by micmurawski** [comment]
@Maxyme I will make a new release with that capability. I would appreciate star 🤩
