### ISSUE TITLE
How to not build dev dependencies ?

### ISSUE THREAD

**Issue by lironsam** [micmurawski/poetry-plugin-lambda-build#12]
Hi,

I try to ignore "[tool.poetry.group.dev.dependencies]" from my pyproject but I'm not able to make it work.
I try to do `poetry build-lambda without dev`  or ` poetry build-lambda without dev.dependencies` but I still get my dev dependencies.

Did I miss something ?

**Comment by micmurawski** [comment]
Try

```
poetry build-lambda without=dev
```

**Comment by lironsam** [comment]
Oh yes, it works.
I've also tested by adding on my pyproject without = "dev" and it works.

I think, it would be great to have an example :).

thank for your cool plugin !
