### ISSUE TITLE
Bug in readme

### ISSUE THREAD

**Issue by marcingryska** [micmurawski/poetry-plugin-lambda-build#14]
We should have 
function-artifact-path = "package.zip"
instead of 
artifact-path = "package.zip"
in a line of 54. I've tried to open PR but no access for me to this repo seems to be.

**Comment by micmurawski** [comment]
I noticed that `artifact-path` should be replaced with `package-artifact-path"`. I will fix that :) THX

The plugin can separate project modules and requirements in two different zips. Parameter `function-artifact-path = "package.zip"` will result in having a python project module without requirements installed in a ZIP file.
`package-artifact-path"` will install everything together all modules and requirements.
