### ISSUE TITLE
Errors on install

### ISSUE THREAD

**Issue by swthor** [micmurawski/poetry-plugin-lambda-build#21]
(f-string: expecting '}' (docker.py, line 91))
unterminated string literal (detected at line 58) (requirements.py, line 58)
unterminated string literal (detected at line 87) (requirements.py, line 87)

Using poetry self add poetry-plugin-lambda-build with python 3.11 received the above 3 errors, all from f strings where the single/double quotes needed to be sorted out.

**Comment by fritjof-b** [comment]
Hi, which version of the plugin are you using?

**Comment by micmurawski** [comment]
This is the error that occurred for me as well some time ago. It looks to me that newer versions of Python ex. 3.12 are more liberal with regards to code formatting, and breaking lines.

I was able to reproduce the error on python3.8 and apply fixes.

**Comment by swthor** [comment]
Cheers! And thanks for making this plugin.
