### ISSUE TITLE
Tokens in commands containing spaces or other special characters are not handled

### ISSUE THREAD

**Issue by allanlewis** [micmurawski/poetry-plugin-lambda-build#24]
There are several places where `cmd.split(" ")` is used to split a command string into a list: `shlex.split(cmd)` is the proper way to do this as it will handle spaces and other special characters in tokens. In general it might be better to specify all commands to be executed via `subprocess` as lists of strings to avoid subtle errors and command injection.

I might work on this issue myself at some point.

**Comment by micmurawski** [comment]
@allanlewis Thanks for the great idea. I will give it a try this weekend to implement this. I've already stumbled into many issues improperly splitting commands, it would save me a lot of time if I knew this earlier.
