### ISSUE TITLE
Persistent ZIP

### ISSUE THREAD

**Issue by dex4er** [micmurawski/poetry-plugin-lambda-build#31]
Hi.

Thank you for the great project. It really makes life easier.

However, I miss the option for creation of persistent ZIP files. Such ZIP file should be exactly the same every time I run `poetry build-lambda --no-checksum` command.

I'm not sure if it is really possible to built such using only Python. As now my workaround is this script:

```sh
#!/usr/bin/env bash

set -e

cd $(dirname $0)
poetry install
poetry build-lambda --no-checksum
rm -rf package
mkdir package
pushd package
unzip ../package.zip
find . -print0 | xargs -0 touch -t 202001010000
popd
rm -f package.zip
zip -r -X package.zip package
rm -rf package
```

The important part is `touch -t 202001010000` that sets the same date for all files in a package and `zip -r -X` which make a new package without extra Unix attributes.

In the end the package has the same byte content after 2nd run.

**Comment by micmurawski** [comment]
Here are my takes on this:

* You can ommit .zip extension in the paths of targets - that will produce outputs as directories not zip files. It can make your scripts easier.
* You can purpose changes in [creation of zip function](https://github.com/micmurawski/poetry-plugin-lambda-build/blob/0bd3f9b47356dc564ad10824dc17a1de47d63ab5/poetry_plugin_lambda_build/zip.py#L17) and [checksum computation function](https://github.com/micmurawski/poetry-plugin-lambda-build/blob/0bd3f9b47356dc564ad10824dc17a1de47d63ab5/poetry_plugin_lambda_build/utils.py#L126)
