### ISSUE TITLE
Running it in a Github Action

### ISSUE THREAD

**Issue by FranGoitia** [micmurawski/poetry-plugin-lambda-build#4]
Hi. Pretty cool extension! I'm wondering how does it work on the context of a github action.

The following steps

```
      - name: Install Poetry Environment
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry config repositories.statsbomb https://statsbomb-368836370510.d.codeartifact.eu-west-2.amazonaws.com/pypi/statsbomb/simple/
          poetry config http-basic.statsbomb aws $(aws codeartifact get-authorization-token  --domain statsbomb --domain-owner 368836370510 | jq -r .authorizationToken)
          poetry self add poetry-plugin-lambda-build
          poetry install

      - name: Package Lambda function
        run: |
          poetry build-lambda
```

return 

```
Run poetry build-lambda
  poetry build-lambda
  shell: /usr/bin/bash -e {0}
  env:
     ***
     ***

'artifact_path'
Error: Process completed with exit code 1.
```

I did set up the `artifact_path` on `pyproject.toml`, and the building works fine locally:
```
[tool.poetry-plugin-lambda-build]
artifact_path = "package.zip"
```

**Comment by micmurawski** [comment]
Hi, I appreciate your feedback!

I would check the following things...

I would run a plugin with the following option to have more logs on what exactly is happening. 

```
poetry build-lambda -vvv
```

My rough guess is that you somehow are running an old version of the package that had this issue you can check the version with the following.

```
pip list | grep poetry
```

The `artifact_path` parameter was replaced by `package_artifact_path` a couple of versions ago. I will add some more descriptive error handling to prevent such errors.
